const types = {
  ADD_DECIMAL: 'ADD_DECIMAL',
  CHANGE_NUMBER: 'CHANGE_NUMBER',
  CHANGE_NUMBER_STATE: 'CHANGE_NUMBER_STATE',
  CHANGE_OPERATOR: 'CHANGE_OPERATOR',
  PERFORM_OPERATION: 'PERFORM_OPERATION',
  REMOVE_DIGIT: 'REMOVE_DIGIT',
  RESET_CALCULATOR: 'RESET_CALCULATOR',
  RESET_CURRENT_NUMBER: 'RESET_CURRENT_NUMBER',
  SHOW_TOTAL: 'SHOW_TOTAL'
}

export default types;
